### ISSUE TITLE
SyntaxError: GNOME Shell 3.12.2 (ArchLinux)

### ISSUE THREAD

**Issue by UO180222** [xtranophilist/gnome-shell-extension-sensors#112] opened 2014-06-20 09:00 UTC
SyntaxError: syntax error

Stack trace:
  @/home/dafero/.local/share/gnome-shell/extensions/temperature@xtranophilist/prefs.js:9
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:86
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:101
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._extensionSelected@resource:///org/gnome/shell/extensionPrefs/main.js:121
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:112
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:245
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:278
  @<main>:1

**Comment by adrianbroher** [comment] 2015-06-09 09:55
Duplicate of #111.

**Closed by adrianbroher** 2015-06-09 09:55 UTC
