### ISSUE TITLE
Error loading preferences dialog

### ISSUE THREAD

**Issue by doGieBert** [xtranophilist/gnome-shell-extension-sensors#105] opened 2014-04-23 14:51 UTC
SyntaxError: syntax error

Stack trace:
  @/home/dgiebert/.local/share/gnome-shell/extensions/temperature@xtranophilist/prefs.js:9
  Application<._getExtensionPrefsModule@/usr/share/gnome-shell/js/extensionPrefs/main.js:86
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@/usr/share/gnome-shell/js/extensionPrefs/main.js:101
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._extensionSelected@/usr/share/gnome-shell/js/extensionPrefs/main.js:121
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@/usr/share/gnome-shell/js/extensionPrefs/main.js:112
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._extensionsLoaded@/usr/share/gnome-shell/js/extensionPrefs/main.js:221
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  _emit@resource:///org/gnome/gjs/modules/signals.js:124
  ExtensionFinder<._extensionsLoaded@/usr/share/gnome-shell/js/misc/extensionUtils.js:178
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  done@/usr/share/gnome-shell/js/misc/fileUtils.js:33
  _collectFromDirectoryAsync/</<@/usr/share/gnome-shell/js/misc/fileUtils.js:51
  onNextFileComplete@/usr/share/gnome-shell/js/misc/fileUtils.js:21
  main@/usr/share/gnome-shell/js/extensionPrefs/main.js:278
  @<command line>:1
  

I am getting this error, after compiling on Ubuntu 14.04 using Gnome 3.10.0.1

**Comment by adrianbroher** [comment] 2015-06-09 09:54
Duplicate of #112.

**Closed by adrianbroher** 2015-06-09 09:54 UTC
